name: Run pintos tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout subdirectories
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu
    - name: build utils
      working-directory: pintos/src/utils
      run: make
    - name: build threads
      working-directory: pintos/src/threads
      run: make
    - name: check threads
      working-directory: pintos/src/threads
      run: make check
