name: Run pintos tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  do:
    runs-on: ubuntu-latest
    env:
      PINTOSDIR: $GITHUB_WORKSPACE/pintos
    steps:
    - uses: actions/checkout@v2
    - name: Checkout subdirectories
      run: git submodule update --init --recursive
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      with:
        platforms: 386
    - name: Setup path
      run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: build utils
      working-directory: pintos/src/utils
      run: make CCPROG=gcc
    - name: build threads
      working-directory: pintos/src/threads
      run: make CCPROG=gcc
    - name: check threads
      working-directory: pintos/src/threads/build
      run: |
        pintos -- run alarm-multiple
        make check CCPROG=gcc
