name: Run pintos tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu
    - name: build utils
      run: |
        ls
        make
      working-directory: pintos/src/utils
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    env:
      PINTOSDIR: $GITHUB_WORKSPACE/pintos
      PATH: $PATH:$GITHUB_WORKSPACE/bin
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}

    steps:
    - name: build threads
      run: make
      working-directory: pintos/src/threads

  tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      PINTOSDIR: $GITHUB_WORKSPACE/pintos
      PATH: $PATH:$GITHUB_WORKSPACE/bin
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}
    
    steps:
    - name: check threads
      run: make check
      working-directory: pintos/src/threads
